spring:
  application:
    name: livid
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${SQLITE_DB_PATH:/data/26-1-mystery-x/buchoipark/data/sqlite/livid.db}
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
  sql:
    init:
      mode: always

app:
  storage:
    dir: ${APP_STORAGE_DIR:/data/26-1-mystery-x/buchoipark/data/uploads}
